package discord

const (
	DiscordEventReady                      = "READY"
	DiscordEventResumed                    = "RESUMED"
	DiscordEventApplicationCommandCreate   = "APPLICATION_COMMAND_CREATE"
	DiscordEventApplicationCommandUpdate   = "APPLICATION_COMMAND_UPDATE"
	DiscordEventApplicationCommandDelete   = "APPLICATION_COMMAND_DELETE"
	DiscordEventGuildMembersChunk          = "GUILD_MEMBERS_CHUNK"
	DiscordEventChannelCreate              = "CHANNEL_CREATE"
	DiscordEventChannelUpdate              = "CHANNEL_UPDATE"
	DiscordEventChannelDelete              = "CHANNEL_DELETE"
	DiscordEventChannelPinsUpdate          = "CHANNEL_PINS_UPDATE"
	DiscordEventThreadCreate               = "THREAD_CREATE"
	DiscordEventThreadUpdate               = "THREAD_UPDATE"
	DiscordEventThreadDelete               = "THREAD_DELETE"
	DiscordEventThreadListSync             = "THREAD_LIST_SYNC"
	DiscordEventThreadMemberUpdate         = "THREAD_MEMBER_UPDATE"
	DiscordEventThreadMembersUpdate        = "THREAD_MEMBERS_UPDATE"
	DiscordEventGuildCreate                = "GUILD_CREATE"
	DiscordEventGuildUpdate                = "GUILD_UPDATE"
	DiscordEventGuildDelete                = "GUILD_DELETE"
	DiscordEventGuildBanAdd                = "GUILD_BAN_ADD"
	DiscordEventGuildBanRemove             = "GUILD_BAN_REMOVE"
	DiscordEventGuildEmojisUpdate          = "GUILD_EMOJIS_UPDATE"
	DiscordEventGuildStickersUpdate        = "GUILD_STICKERS_UPDATE"
	DiscordEventGuildIntegrationsUpdate    = "GUILD_INTEGRATIONS_UPDATE"
	DiscordEventGuildMemberAdd             = "GUILD_MEMBER_ADD"
	DiscordEventGuildMemberRemove          = "GUILD_MEMBER_REMOVE"
	DiscordEventGuildMemberUpdate          = "GUILD_MEMBER_UPDATE"
	DiscordEventGuildRoleCreate            = "GUILD_ROLE_CREATE"
	DiscordEventGuildRoleUpdate            = "GUILD_ROLE_UPDATE"
	DiscordEventGuildRoleDelete            = "GUILD_ROLE_DELETE"
	DiscordEventIntegrationCreate          = "INTEGRATION_CREATE"
	DiscordEventIntegrationUpdate          = "INTEGRATION_UPDATE"
	DiscordEventIntegrationDelete          = "INTEGRATION_DELETE"
	DiscordEventInteractionCreate          = "INTERACTION_CREATE"
	DiscordEventInviteCreate               = "INVITE_CREATE"
	DiscordEventInviteDelete               = "INVITE_DELETE"
	DiscordEventMessageCreate              = "MESSAGE_CREATE"
	DiscordEventMessageUpdate              = "MESSAGE_UPDATE"
	DiscordEventMessageDelete              = "MESSAGE_DELETE"
	DiscordEventMessageDeleteBulk          = "MESSAGE_DELETE_BULK"
	DiscordEventMessageReactionAdd         = "MESSAGE_REACTION_ADD"
	DiscordEventMessageReactionRemove      = "MESSAGE_REACTION_REMOVE"
	DiscordEventMessageReactionRemoveAll   = "MESSAGE_REACTION_REMOVE_ALL"
	DiscordEventMessageReactionRemoveEmoji = "MESSAGE_REACTION_REMOVE_EMOJI"
	DiscordEventPresenceUpdate             = "PRESENCE_UPDATE"
	DiscordEventStageInstanceCreate        = "STAGE_INSTANCE_CREATE"
	DiscordEventStageInstanceUpdate        = "STAGE_INSTANCE_UPDATE"
	DiscordEventStageInstanceDelete        = "STAGE_INSTANCE_DELETE"
	DiscordEventTypingStart                = "TYPING_START"
	DiscordEventUserUpdate                 = "USER_UPDATE"
	DiscordEventVoiceStateUpdate           = "VOICE_STATE_UPDATE"
	DiscordEventVoiceServerUpdate          = "VOICE_SERVER_UPDATE"
	DiscordEventWebhookUpdate              = "WEBHOOKS_UPDATE"
	DiscordEventGuildJoinRequestDelete     = "GUILD_JOIN_REQUEST_DELETE"

	DiscordEventEntitlementCreate = "ENTITLEMENT_CREATE"
	DiscordEventEntitlementUpdate = "ENTITLEMENT_UPDATE"
	DiscordEventEntitlementDelete = "ENTITLEMENT_DELETE"

	DiscordEventGuildJoin        = "GUILD_JOIN"
	DiscordEventGuildAvailable   = "GUILD_AVAILABLE"
	DiscordEventGuildLeave       = "GUILD_LEAVE"
	DiscordEventGuildUnavailable = "GUILD_UNAVAILABLE"
)
