// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: sandwich.proto

package sandwich

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sandwich_Listen_FullMethodName                = "/sandwich.Sandwich/Listen"
	Sandwich_RelayMessage_FullMethodName          = "/sandwich.Sandwich/RelayMessage"
	Sandwich_ReloadConfiguration_FullMethodName   = "/sandwich.Sandwich/ReloadConfiguration"
	Sandwich_FetchApplication_FullMethodName      = "/sandwich.Sandwich/FetchApplication"
	Sandwich_StartApplication_FullMethodName      = "/sandwich.Sandwich/StartApplication"
	Sandwich_StopApplication_FullMethodName       = "/sandwich.Sandwich/StopApplication"
	Sandwich_CreateApplication_FullMethodName     = "/sandwich.Sandwich/CreateApplication"
	Sandwich_DeleteApplication_FullMethodName     = "/sandwich.Sandwich/DeleteApplication"
	Sandwich_RequestGuildChunk_FullMethodName     = "/sandwich.Sandwich/RequestGuildChunk"
	Sandwich_SendWebsocketMessage_FullMethodName  = "/sandwich.Sandwich/SendWebsocketMessage"
	Sandwich_WhereIsGuild_FullMethodName          = "/sandwich.Sandwich/WhereIsGuild"
	Sandwich_FetchAllGuildIDs_FullMethodName      = "/sandwich.Sandwich/FetchAllGuildIDs"
	Sandwich_FetchGuild_FullMethodName            = "/sandwich.Sandwich/FetchGuild"
	Sandwich_FetchGuildMember_FullMethodName      = "/sandwich.Sandwich/FetchGuildMember"
	Sandwich_FetchGuildChannel_FullMethodName     = "/sandwich.Sandwich/FetchGuildChannel"
	Sandwich_FetchGuildRole_FullMethodName        = "/sandwich.Sandwich/FetchGuildRole"
	Sandwich_FetchGuildEmoji_FullMethodName       = "/sandwich.Sandwich/FetchGuildEmoji"
	Sandwich_FetchGuildSticker_FullMethodName     = "/sandwich.Sandwich/FetchGuildSticker"
	Sandwich_FetchGuildVoiceState_FullMethodName  = "/sandwich.Sandwich/FetchGuildVoiceState"
	Sandwich_FetchUser_FullMethodName             = "/sandwich.Sandwich/FetchUser"
	Sandwich_FetchUserMutualGuilds_FullMethodName = "/sandwich.Sandwich/FetchUserMutualGuilds"
	Sandwich_FetchVoiceStates_FullMethodName      = "/sandwich.Sandwich/FetchVoiceStates"
)

// SandwichClient is the client API for Sandwich service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SandwichClient interface {
	// Listen delivers information to consumers.
	Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListenResponse], error)
	// RelayMessage creates a new event and sends it immediately back to Applications.
	RelayMessage(ctx context.Context, in *RelayMessageRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	// ReloadConfiguration reloads the configuration.
	ReloadConfiguration(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BaseResponse, error)
	// FetchApplication returns the Application Configuration.
	FetchApplication(ctx context.Context, in *ApplicationIdentifier, opts ...grpc.CallOption) (*FetchApplicationResponse, error)
	// StartApplication starts a Application.
	StartApplication(ctx context.Context, in *ApplicationIdentifierWithBlocking, opts ...grpc.CallOption) (*BaseResponse, error)
	// StopApplication stops a Application.
	StopApplication(ctx context.Context, in *ApplicationIdentifierWithBlocking, opts ...grpc.CallOption) (*BaseResponse, error)
	// CreateApplication creates a new Application.
	CreateApplication(ctx context.Context, in *CreateApplicationRequest, opts ...grpc.CallOption) (*SandwichApplication, error)
	// DeleteApplication deletes a Application.
	DeleteApplication(ctx context.Context, in *ApplicationIdentifier, opts ...grpc.CallOption) (*BaseResponse, error)
	// RequestGuildChunk requests a guild chunk.
	RequestGuildChunk(ctx context.Context, in *RequestGuildChunkRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	// SendWebsocketMessage sends a websocket message to discord from a specific shard.
	SendWebsocketMessage(ctx context.Context, in *SendWebsocketMessageRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	// WhereIsGuild returns a list of WhereIsGuildLocations based on guildId.
	WhereIsGuild(ctx context.Context, in *WhereIsGuildRequest, opts ...grpc.CallOption) (*WhereIsGuildResponse, error)
	FetchAllGuildIDs(ctx context.Context, in *FetchGuildIDsRequest, opts ...grpc.CallOption) (*FetchGuildIDsResponse, error)
	FetchGuild(ctx context.Context, in *FetchGuildRequest, opts ...grpc.CallOption) (*FetchGuildResponse, error)
	FetchGuildMember(ctx context.Context, in *FetchGuildMemberRequest, opts ...grpc.CallOption) (*FetchGuildMemberResponse, error)
	FetchGuildChannel(ctx context.Context, in *FetchGuildChannelRequest, opts ...grpc.CallOption) (*FetchGuildChannelResponse, error)
	FetchGuildRole(ctx context.Context, in *FetchGuildRoleRequest, opts ...grpc.CallOption) (*FetchGuildRoleResponse, error)
	FetchGuildEmoji(ctx context.Context, in *FetchGuildEmojiRequest, opts ...grpc.CallOption) (*FetchGuildEmojiResponse, error)
	FetchGuildSticker(ctx context.Context, in *FetchGuildStickerRequest, opts ...grpc.CallOption) (*FetchGuildStickerResponse, error)
	FetchGuildVoiceState(ctx context.Context, in *FetchGuildVoiceStateRequest, opts ...grpc.CallOption) (*FetchGuildVoiceStateResponse, error)
	FetchUser(ctx context.Context, in *FetchUserRequest, opts ...grpc.CallOption) (*FetchUserResponse, error)
	FetchUserMutualGuilds(ctx context.Context, in *FetchUserMutualGuildsRequest, opts ...grpc.CallOption) (*FetchUserMutualGuildsResponse, error)
	FetchVoiceStates(ctx context.Context, in *FetchVoiceStatesRequest, opts ...grpc.CallOption) (*FetchVoiceStatesResponse, error)
}

type sandwichClient struct {
	cc grpc.ClientConnInterface
}

func NewSandwichClient(cc grpc.ClientConnInterface) SandwichClient {
	return &sandwichClient{cc}
}

func (c *sandwichClient) Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListenResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sandwich_ServiceDesc.Streams[0], Sandwich_Listen_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListenRequest, ListenResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandwich_ListenClient = grpc.ServerStreamingClient[ListenResponse]

func (c *sandwichClient) RelayMessage(ctx context.Context, in *RelayMessageRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, Sandwich_RelayMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) ReloadConfiguration(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, Sandwich_ReloadConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) FetchApplication(ctx context.Context, in *ApplicationIdentifier, opts ...grpc.CallOption) (*FetchApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchApplicationResponse)
	err := c.cc.Invoke(ctx, Sandwich_FetchApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) StartApplication(ctx context.Context, in *ApplicationIdentifierWithBlocking, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, Sandwich_StartApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) StopApplication(ctx context.Context, in *ApplicationIdentifierWithBlocking, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, Sandwich_StopApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) CreateApplication(ctx context.Context, in *CreateApplicationRequest, opts ...grpc.CallOption) (*SandwichApplication, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandwichApplication)
	err := c.cc.Invoke(ctx, Sandwich_CreateApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) DeleteApplication(ctx context.Context, in *ApplicationIdentifier, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, Sandwich_DeleteApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) RequestGuildChunk(ctx context.Context, in *RequestGuildChunkRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, Sandwich_RequestGuildChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) SendWebsocketMessage(ctx context.Context, in *SendWebsocketMessageRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, Sandwich_SendWebsocketMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) WhereIsGuild(ctx context.Context, in *WhereIsGuildRequest, opts ...grpc.CallOption) (*WhereIsGuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhereIsGuildResponse)
	err := c.cc.Invoke(ctx, Sandwich_WhereIsGuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) FetchAllGuildIDs(ctx context.Context, in *FetchGuildIDsRequest, opts ...grpc.CallOption) (*FetchGuildIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchGuildIDsResponse)
	err := c.cc.Invoke(ctx, Sandwich_FetchAllGuildIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) FetchGuild(ctx context.Context, in *FetchGuildRequest, opts ...grpc.CallOption) (*FetchGuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchGuildResponse)
	err := c.cc.Invoke(ctx, Sandwich_FetchGuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) FetchGuildMember(ctx context.Context, in *FetchGuildMemberRequest, opts ...grpc.CallOption) (*FetchGuildMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchGuildMemberResponse)
	err := c.cc.Invoke(ctx, Sandwich_FetchGuildMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) FetchGuildChannel(ctx context.Context, in *FetchGuildChannelRequest, opts ...grpc.CallOption) (*FetchGuildChannelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchGuildChannelResponse)
	err := c.cc.Invoke(ctx, Sandwich_FetchGuildChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) FetchGuildRole(ctx context.Context, in *FetchGuildRoleRequest, opts ...grpc.CallOption) (*FetchGuildRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchGuildRoleResponse)
	err := c.cc.Invoke(ctx, Sandwich_FetchGuildRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) FetchGuildEmoji(ctx context.Context, in *FetchGuildEmojiRequest, opts ...grpc.CallOption) (*FetchGuildEmojiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchGuildEmojiResponse)
	err := c.cc.Invoke(ctx, Sandwich_FetchGuildEmoji_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) FetchGuildSticker(ctx context.Context, in *FetchGuildStickerRequest, opts ...grpc.CallOption) (*FetchGuildStickerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchGuildStickerResponse)
	err := c.cc.Invoke(ctx, Sandwich_FetchGuildSticker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) FetchGuildVoiceState(ctx context.Context, in *FetchGuildVoiceStateRequest, opts ...grpc.CallOption) (*FetchGuildVoiceStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchGuildVoiceStateResponse)
	err := c.cc.Invoke(ctx, Sandwich_FetchGuildVoiceState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) FetchUser(ctx context.Context, in *FetchUserRequest, opts ...grpc.CallOption) (*FetchUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchUserResponse)
	err := c.cc.Invoke(ctx, Sandwich_FetchUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) FetchUserMutualGuilds(ctx context.Context, in *FetchUserMutualGuildsRequest, opts ...grpc.CallOption) (*FetchUserMutualGuildsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchUserMutualGuildsResponse)
	err := c.cc.Invoke(ctx, Sandwich_FetchUserMutualGuilds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandwichClient) FetchVoiceStates(ctx context.Context, in *FetchVoiceStatesRequest, opts ...grpc.CallOption) (*FetchVoiceStatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchVoiceStatesResponse)
	err := c.cc.Invoke(ctx, Sandwich_FetchVoiceStates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandwichServer is the server API for Sandwich service.
// All implementations must embed UnimplementedSandwichServer
// for forward compatibility.
type SandwichServer interface {
	// Listen delivers information to consumers.
	Listen(*ListenRequest, grpc.ServerStreamingServer[ListenResponse]) error
	// RelayMessage creates a new event and sends it immediately back to Applications.
	RelayMessage(context.Context, *RelayMessageRequest) (*BaseResponse, error)
	// ReloadConfiguration reloads the configuration.
	ReloadConfiguration(context.Context, *emptypb.Empty) (*BaseResponse, error)
	// FetchApplication returns the Application Configuration.
	FetchApplication(context.Context, *ApplicationIdentifier) (*FetchApplicationResponse, error)
	// StartApplication starts a Application.
	StartApplication(context.Context, *ApplicationIdentifierWithBlocking) (*BaseResponse, error)
	// StopApplication stops a Application.
	StopApplication(context.Context, *ApplicationIdentifierWithBlocking) (*BaseResponse, error)
	// CreateApplication creates a new Application.
	CreateApplication(context.Context, *CreateApplicationRequest) (*SandwichApplication, error)
	// DeleteApplication deletes a Application.
	DeleteApplication(context.Context, *ApplicationIdentifier) (*BaseResponse, error)
	// RequestGuildChunk requests a guild chunk.
	RequestGuildChunk(context.Context, *RequestGuildChunkRequest) (*BaseResponse, error)
	// SendWebsocketMessage sends a websocket message to discord from a specific shard.
	SendWebsocketMessage(context.Context, *SendWebsocketMessageRequest) (*BaseResponse, error)
	// WhereIsGuild returns a list of WhereIsGuildLocations based on guildId.
	WhereIsGuild(context.Context, *WhereIsGuildRequest) (*WhereIsGuildResponse, error)
	FetchAllGuildIDs(context.Context, *FetchGuildIDsRequest) (*FetchGuildIDsResponse, error)
	FetchGuild(context.Context, *FetchGuildRequest) (*FetchGuildResponse, error)
	FetchGuildMember(context.Context, *FetchGuildMemberRequest) (*FetchGuildMemberResponse, error)
	FetchGuildChannel(context.Context, *FetchGuildChannelRequest) (*FetchGuildChannelResponse, error)
	FetchGuildRole(context.Context, *FetchGuildRoleRequest) (*FetchGuildRoleResponse, error)
	FetchGuildEmoji(context.Context, *FetchGuildEmojiRequest) (*FetchGuildEmojiResponse, error)
	FetchGuildSticker(context.Context, *FetchGuildStickerRequest) (*FetchGuildStickerResponse, error)
	FetchGuildVoiceState(context.Context, *FetchGuildVoiceStateRequest) (*FetchGuildVoiceStateResponse, error)
	FetchUser(context.Context, *FetchUserRequest) (*FetchUserResponse, error)
	FetchUserMutualGuilds(context.Context, *FetchUserMutualGuildsRequest) (*FetchUserMutualGuildsResponse, error)
	FetchVoiceStates(context.Context, *FetchVoiceStatesRequest) (*FetchVoiceStatesResponse, error)
	mustEmbedUnimplementedSandwichServer()
}

// UnimplementedSandwichServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandwichServer struct{}

func (UnimplementedSandwichServer) Listen(*ListenRequest, grpc.ServerStreamingServer[ListenResponse]) error {
	return status.Error(codes.Unimplemented, "method Listen not implemented")
}
func (UnimplementedSandwichServer) RelayMessage(context.Context, *RelayMessageRequest) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RelayMessage not implemented")
}
func (UnimplementedSandwichServer) ReloadConfiguration(context.Context, *emptypb.Empty) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadConfiguration not implemented")
}
func (UnimplementedSandwichServer) FetchApplication(context.Context, *ApplicationIdentifier) (*FetchApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchApplication not implemented")
}
func (UnimplementedSandwichServer) StartApplication(context.Context, *ApplicationIdentifierWithBlocking) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartApplication not implemented")
}
func (UnimplementedSandwichServer) StopApplication(context.Context, *ApplicationIdentifierWithBlocking) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopApplication not implemented")
}
func (UnimplementedSandwichServer) CreateApplication(context.Context, *CreateApplicationRequest) (*SandwichApplication, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateApplication not implemented")
}
func (UnimplementedSandwichServer) DeleteApplication(context.Context, *ApplicationIdentifier) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteApplication not implemented")
}
func (UnimplementedSandwichServer) RequestGuildChunk(context.Context, *RequestGuildChunkRequest) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestGuildChunk not implemented")
}
func (UnimplementedSandwichServer) SendWebsocketMessage(context.Context, *SendWebsocketMessageRequest) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendWebsocketMessage not implemented")
}
func (UnimplementedSandwichServer) WhereIsGuild(context.Context, *WhereIsGuildRequest) (*WhereIsGuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WhereIsGuild not implemented")
}
func (UnimplementedSandwichServer) FetchAllGuildIDs(context.Context, *FetchGuildIDsRequest) (*FetchGuildIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchAllGuildIDs not implemented")
}
func (UnimplementedSandwichServer) FetchGuild(context.Context, *FetchGuildRequest) (*FetchGuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchGuild not implemented")
}
func (UnimplementedSandwichServer) FetchGuildMember(context.Context, *FetchGuildMemberRequest) (*FetchGuildMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchGuildMember not implemented")
}
func (UnimplementedSandwichServer) FetchGuildChannel(context.Context, *FetchGuildChannelRequest) (*FetchGuildChannelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchGuildChannel not implemented")
}
func (UnimplementedSandwichServer) FetchGuildRole(context.Context, *FetchGuildRoleRequest) (*FetchGuildRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchGuildRole not implemented")
}
func (UnimplementedSandwichServer) FetchGuildEmoji(context.Context, *FetchGuildEmojiRequest) (*FetchGuildEmojiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchGuildEmoji not implemented")
}
func (UnimplementedSandwichServer) FetchGuildSticker(context.Context, *FetchGuildStickerRequest) (*FetchGuildStickerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchGuildSticker not implemented")
}
func (UnimplementedSandwichServer) FetchGuildVoiceState(context.Context, *FetchGuildVoiceStateRequest) (*FetchGuildVoiceStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchGuildVoiceState not implemented")
}
func (UnimplementedSandwichServer) FetchUser(context.Context, *FetchUserRequest) (*FetchUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchUser not implemented")
}
func (UnimplementedSandwichServer) FetchUserMutualGuilds(context.Context, *FetchUserMutualGuildsRequest) (*FetchUserMutualGuildsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchUserMutualGuilds not implemented")
}
func (UnimplementedSandwichServer) FetchVoiceStates(context.Context, *FetchVoiceStatesRequest) (*FetchVoiceStatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchVoiceStates not implemented")
}
func (UnimplementedSandwichServer) mustEmbedUnimplementedSandwichServer() {}
func (UnimplementedSandwichServer) testEmbeddedByValue()                  {}

// UnsafeSandwichServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandwichServer will
// result in compilation errors.
type UnsafeSandwichServer interface {
	mustEmbedUnimplementedSandwichServer()
}

func RegisterSandwichServer(s grpc.ServiceRegistrar, srv SandwichServer) {
	// If the following call panics, it indicates UnimplementedSandwichServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sandwich_ServiceDesc, srv)
}

func _Sandwich_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandwichServer).Listen(m, &grpc.GenericServerStream[ListenRequest, ListenResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandwich_ListenServer = grpc.ServerStreamingServer[ListenResponse]

func _Sandwich_RelayMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).RelayMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_RelayMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).RelayMessage(ctx, req.(*RelayMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_ReloadConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).ReloadConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_ReloadConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).ReloadConfiguration(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_FetchApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).FetchApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_FetchApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).FetchApplication(ctx, req.(*ApplicationIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_StartApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationIdentifierWithBlocking)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).StartApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_StartApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).StartApplication(ctx, req.(*ApplicationIdentifierWithBlocking))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_StopApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationIdentifierWithBlocking)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).StopApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_StopApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).StopApplication(ctx, req.(*ApplicationIdentifierWithBlocking))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_CreateApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).CreateApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_CreateApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).CreateApplication(ctx, req.(*CreateApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_DeleteApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).DeleteApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_DeleteApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).DeleteApplication(ctx, req.(*ApplicationIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_RequestGuildChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGuildChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).RequestGuildChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_RequestGuildChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).RequestGuildChunk(ctx, req.(*RequestGuildChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_SendWebsocketMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendWebsocketMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).SendWebsocketMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_SendWebsocketMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).SendWebsocketMessage(ctx, req.(*SendWebsocketMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_WhereIsGuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhereIsGuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).WhereIsGuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_WhereIsGuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).WhereIsGuild(ctx, req.(*WhereIsGuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_FetchAllGuildIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchGuildIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).FetchAllGuildIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_FetchAllGuildIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).FetchAllGuildIDs(ctx, req.(*FetchGuildIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_FetchGuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchGuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).FetchGuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_FetchGuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).FetchGuild(ctx, req.(*FetchGuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_FetchGuildMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchGuildMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).FetchGuildMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_FetchGuildMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).FetchGuildMember(ctx, req.(*FetchGuildMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_FetchGuildChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchGuildChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).FetchGuildChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_FetchGuildChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).FetchGuildChannel(ctx, req.(*FetchGuildChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_FetchGuildRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchGuildRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).FetchGuildRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_FetchGuildRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).FetchGuildRole(ctx, req.(*FetchGuildRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_FetchGuildEmoji_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchGuildEmojiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).FetchGuildEmoji(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_FetchGuildEmoji_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).FetchGuildEmoji(ctx, req.(*FetchGuildEmojiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_FetchGuildSticker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchGuildStickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).FetchGuildSticker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_FetchGuildSticker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).FetchGuildSticker(ctx, req.(*FetchGuildStickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_FetchGuildVoiceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchGuildVoiceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).FetchGuildVoiceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_FetchGuildVoiceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).FetchGuildVoiceState(ctx, req.(*FetchGuildVoiceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_FetchUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).FetchUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_FetchUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).FetchUser(ctx, req.(*FetchUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_FetchUserMutualGuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchUserMutualGuildsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).FetchUserMutualGuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_FetchUserMutualGuilds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).FetchUserMutualGuilds(ctx, req.(*FetchUserMutualGuildsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandwich_FetchVoiceStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchVoiceStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandwichServer).FetchVoiceStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandwich_FetchVoiceStates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandwichServer).FetchVoiceStates(ctx, req.(*FetchVoiceStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sandwich_ServiceDesc is the grpc.ServiceDesc for Sandwich service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sandwich_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandwich.Sandwich",
	HandlerType: (*SandwichServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RelayMessage",
			Handler:    _Sandwich_RelayMessage_Handler,
		},
		{
			MethodName: "ReloadConfiguration",
			Handler:    _Sandwich_ReloadConfiguration_Handler,
		},
		{
			MethodName: "FetchApplication",
			Handler:    _Sandwich_FetchApplication_Handler,
		},
		{
			MethodName: "StartApplication",
			Handler:    _Sandwich_StartApplication_Handler,
		},
		{
			MethodName: "StopApplication",
			Handler:    _Sandwich_StopApplication_Handler,
		},
		{
			MethodName: "CreateApplication",
			Handler:    _Sandwich_CreateApplication_Handler,
		},
		{
			MethodName: "DeleteApplication",
			Handler:    _Sandwich_DeleteApplication_Handler,
		},
		{
			MethodName: "RequestGuildChunk",
			Handler:    _Sandwich_RequestGuildChunk_Handler,
		},
		{
			MethodName: "SendWebsocketMessage",
			Handler:    _Sandwich_SendWebsocketMessage_Handler,
		},
		{
			MethodName: "WhereIsGuild",
			Handler:    _Sandwich_WhereIsGuild_Handler,
		},
		{
			MethodName: "FetchAllGuildIDs",
			Handler:    _Sandwich_FetchAllGuildIDs_Handler,
		},
		{
			MethodName: "FetchGuild",
			Handler:    _Sandwich_FetchGuild_Handler,
		},
		{
			MethodName: "FetchGuildMember",
			Handler:    _Sandwich_FetchGuildMember_Handler,
		},
		{
			MethodName: "FetchGuildChannel",
			Handler:    _Sandwich_FetchGuildChannel_Handler,
		},
		{
			MethodName: "FetchGuildRole",
			Handler:    _Sandwich_FetchGuildRole_Handler,
		},
		{
			MethodName: "FetchGuildEmoji",
			Handler:    _Sandwich_FetchGuildEmoji_Handler,
		},
		{
			MethodName: "FetchGuildSticker",
			Handler:    _Sandwich_FetchGuildSticker_Handler,
		},
		{
			MethodName: "FetchGuildVoiceState",
			Handler:    _Sandwich_FetchGuildVoiceState_Handler,
		},
		{
			MethodName: "FetchUser",
			Handler:    _Sandwich_FetchUser_Handler,
		},
		{
			MethodName: "FetchUserMutualGuilds",
			Handler:    _Sandwich_FetchUserMutualGuilds_Handler,
		},
		{
			MethodName: "FetchVoiceStates",
			Handler:    _Sandwich_FetchVoiceStates_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Listen",
			Handler:       _Sandwich_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sandwich.proto",
}
